version: '3.1'

services:

  go_api:
    restart: always
    container_name: go_api
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - local

  db:
    image: mysql
    restart: always
    container_name: db_mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Jakarta'
    volumes:
        - ./mysql/data/sql_data/:/docker-entrypoint-initdb.d
        - ./mysql/data/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - local


volumes:
    db_data:

networks:
  local:
    driver: bridge
